Final project
Vova4o/go_final_project pull request #1
Opened 2024-05-05 09:22 UTC by Vova4o

В прошлом репозитория пытался добавить CI но тесты почему-то не хотели проходить на гите.
В исправленном readme.MD написано все что есть в программе.

На моей машине все работает и все тесты проходят. Образ докера тоже собрался.

2024-05-05 15:13 UTC, dirtymew requested changes
Привет Владимир

отличная работа, супер что:
- добавил логирование
- тесты
- разделил на пакеты как принято в go

есть конечно что поправить 

улучшения по архитектуре скорее совет - не обязательно но я бы переделал

по теста в actions - их можно сделать но учти что это end-to-end тесты - тебе нужно поднять приложение одним степом и потом запустить тесты напротив него...  это возможно но не обязательно в рамках этого проекта

2024-05-05 15:13 UTC, dirtymew commented on internal/database/storage.go
> +
нужно ошибку из rows.Err обработать - ну или QueryRow использовать

2024-05-05 15:13 UTC, dirtymew commented on internal/database/storage.go
> +func FindTask(db *sql.DB, search string) (models.DBTask, error) {
тут лучше id а не search ...

2024-05-05 15:13 UTC, dirtymew commented on internal/database/storage.go
> +	rows, err := db.Query(query, search)
тут нам одна запись нужна - лучше QueryRow

2024-05-05 15:13 UTC, dirtymew commented on internal/database/storage.go
> +		return task, err
лучше явно вернуть пустую структуру

2024-05-05 15:13 UTC, dirtymew commented on internal/database/storage.go
> +	return tasks, nil
нужно ошибку обработать rows.Err

2024-05-05 15:13 UTC, dirtymew commented on internal/database/storage.go
> +func TasksByDate(db *sql.DB, date string) ([]models.DBTask, error) {
мб тут не строку передавать а тип time

2024-05-05 15:13 UTC, dirtymew commented on internal/database/storage.go
> +
я бы выделил storege в struct - storage {db: *sql.DB}

и все методы обьявил бы у нее.

тогда не нужно было бы db везде передавать

2024-05-05 15:13 UTC, dirtymew commented on internal/database/storage.go
> +	query := fmt.Sprintf("SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date LIMIT 10 OFFSET %d", offset)
LIMIT в константу лучше вынести

2024-05-05 15:13 UTC, dirtymew commented on internal/database/storage.go
> +func NextDate(now time.Time, date string, repeat string) (string, error) {
это и дельше не относится к бд и хранению - лучще в отдельный пакет унести

2024-05-05 15:13 UTC, dirtymew commented on internal/database/storage.go
> +func DoneTask(db *sql.DB, id string) error {
это я думаю не метод хранилища - лучше на другом слое сделать - комбинацией методов storage-a

2024-05-05 15:13 UTC, dirtymew commented on internal/handlers/addtask.go
> +func checkTask(t task) (task, error) {
это похоже на метод структуры task

2024-05-06 08:14 UTC, Vova4o commented on internal/database/storage.go
> +
Убрал Query и вроде все ошибки встали на место.

2024-05-06 08:15 UTC, Vova4o commented on internal/database/storage.go
> +func FindTask(db *sql.DB, search string) (models.DBTask, error) {
Поправил. Да исходя из функции id более предпочтительно.

2024-05-06 08:15 UTC, Vova4o commented on internal/database/storage.go
> +	rows, err := db.Query(query, search)
Да, я об этом не подумал.

Данная ошибка исправлена и кода стало меньше.

2024-05-06 08:18 UTC, Vova4o commented on internal/database/storage.go
> +		return task, err
Надеюсь я правильно сделал. Новые строки 101 и 103
То есть если позвать просто task то вернется nil? так чтоли?

2024-05-06 08:21 UTC, Vova4o commented on internal/database/storage.go
> +	return tasks, nil
Ошибку обработал, но не совсем уверен что мы там возвращаем nil, err
nil как то очень не очень...

2024-05-06 08:31 UTC, Vova4o commented on internal/database/storage.go
> +func TasksByDate(db *sql.DB, date string) ([]models.DBTask, error) {
А надо ли? Мы хотим отправить запрос к БД, как по мне чем меньше операций в БД тем лучше.
Проверка и парсинг проходят до того как данные попадают в БД ручку, что как мне кажется даже лучше.
Но можно и переделать это не принципиально.

2024-05-06 08:44 UTC, Vova4o commented on internal/database/storage.go
> +func NextDate(now time.Time, date string, repeat string) (string, error) {
Я об этом думал, но оно как-то прижилось там...

2024-05-06 08:51 UTC, Vova4o commented on internal/handlers/addtask.go
> +func checkTask(t task) (task, error) {
Я понял, в моем случае я забирал всю структуру в функцию и работал с ней, а тут получается мы получаем указатель на структуру и потом работаем с теми данными не передавая их ни куда.

2024-05-06 08:51 UTC, Vova4o commented on internal/database/storage.go
> +	query := fmt.Sprintf("SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date LIMIT 10 OFFSET %d", offset)
Сделано

2024-05-06 10:36 UTC, Vova4o commented on internal/database/storage.go
> +
Как маленькое дополнение превращается в переписку всего кода 8)
В общем пришлось менять всю БД, делать интерфейс и менять все хендлеры, что повлекло за собой изменения в запуске сервера... Так как все эти структуры и переменные надо иницииализировать...

2024-05-06 11:07 UTC, Vova4o commented on internal/database/storage.go
> +func DoneTask(db *sql.DB, id string) error {
Вот тут не совсем понимаю...

У нас же запрос идет к БД и соответсвенно мы с бд и работаем

2024-05-06 11:11 UTC, Vova4o commented
Антон, привет!

Спасибо огромное за замечания, я вроде все поправил, кроме метода DoneTask. Не совсем понял что с ним надо сделать. 

Все изменения в том же ПР.

2024-05-06 20:37 UTC, dirtymew approved these changes
Привет Владимир

Все супер - одна из лучших работ которые довелось видеть на текущий момент

отдельный респект за юнит тесты

Зачет с + 

Удачи в обучении!

2024-05-06 20:37 UTC, dirtymew commented on go.mod
> +go 1.22.1
или в докере поднять или тут понизить до go 1.22

2024-05-06 20:37 UTC, dirtymew commented on internal/database/storage.go
> +
Архитектура и дизайн решения  очень важны и ошибки в них очень дорогие!

Вот это прям отлично что сделал - прям получил на практике дополнительный материал

Кроме как руками  порой понять сложно некоторое вещи - супер что не поленился и сделал такой "рефакторинг" - молодец

2024-05-06 20:37 UTC, dirtymew commented on internal/database/storage.go
> +func DoneTask(db *sql.DB, id string) error {
*переделывать не обязательно 

попытаюсь обьяснить 

при проектировании сложных систем часто используется компонетный подход - это когда есть четкое разделение программы на модули по их функциональности. Это отличный метод позволяет переиспользовать , качетсвенно тестировать код итд

тут например мы модем выделить абстракцию(storage) над бд котороя будет выполнять классические CRUD операции и все.
и выделить слой/модуль(service) который будет выполнять сложную логику - к сожалению в этом примере ее не так много - только вот один метод Done такой - думаю авторы поэтому его и включили в задание чтобы намекнуть на определенные моменты...

те в твоем случае это в handler-е taskDone нужно было сделать комбинацией методов get и delete стоража + стало бы понятнее зачем nextdate в отдельном пакете)



но это конечно не единственно верный способ решения )

2024-05-06 20:37 UTC, dirtymew commented on internal/handlers/addtask.go
> +func checkTask(t task) (task, error) {
ну да

можно делать так err := task.Validate() ...

2024-05-06 20:37 UTC, dirtymew commented on internal/database/storage.go
> +	return tasks, nil
это как раз по канону go - тут все ок

2024-05-06 20:37 UTC, dirtymew commented on logs.log
> +[GIN] 2024/05/06 - 15:00:46 | 400 |     347.958µs |             ::1 | POST     "/api/task"
это в .gitignore )

2024-05-06 20:37 UTC, dirtymew commented on go.mod
> +go 1.22.1
@Vova4o тут забыл - но не буде возвращать за такое)

2024-05-06 20:37 UTC, dirtymew commented on internal/database/storage_test.go
> +func TestNextDate(t *testing.T) {
тест надо в nextdate перенести теперь

2024-05-06 20:37 UTC, dirtymew commented on internal/server/server.go
> +			panic(err)
log.Fatal

2024-05-07 11:12 UTC, merged